I_NUMBER = 5

MASSA_AVIAO = 3350
ACELERACAO_GRAVITICA = 9.80665
PESO = MASSA_AVIAO*ACELERACAO_GRAVITICA

FATOR_DE_CARGA = 4
VELOCIDADE_DO_AVIAO = 152

COEFICIENTE_DE_MOMENTO = -0.15

ENVERGADURA = 12.8-0.2*(I_NUMBER-1)
CORDA_MEDIA = 1.4+0.02*(I_NUMBER-1)
COMPRIMENTO_FUSELAGEM = 5.1+0.02*(I_NUMBER-1)
AREA_ALAR = ENVERGADURA*CORDA_MEDIA

CENTRO_GRAVIDADE = 0.05*CORDA_MEDIA
CENTRO_AERODINAMICO = -0.5

DENSIDADE = 1.225

ESPESSURA_CAMADA = 0.05e-3

MASSA_INERCIA_1 = 250
POSICAO_INERCIA_1 = 0.6
MASSA_INERCIA_2 = 250
POSICAO_INERCIA_2 = 2.2
MASSA_INERCIA_3 = 150
POSICAO_INERCIA_3 = COMPRIMENTO_FUSELAGEM

#Cargas de inercia
FORCA_1 = MASSA_INERCIA_1*ACELERACAO_GRAVITICA*FATOR_DE_CARGA
FORCA_2 = MASSA_INERCIA_2*ACELERACAO_GRAVITICA*FATOR_DE_CARGA
FORCA_3 = MASSA_INERCIA_3*ACELERACAO_GRAVITICA*FATOR_DE_CARGA

MOMENTO_EMPENAGEM_HORIZONTAL = 0.5*DENSIDADE*VELOCIDADE_DO_AVIAO**2*AREA_ALAR*CORDA_MEDIA*COEFICIENTE_DE_MOMENTO
CARGA_EMPENAGEM_HORIZONTAL = (MOMENTO_EMPENAGEM_HORIZONTAL-FATOR_DE_CARGA*PESO*CENTRO_GRAVIDADE)/(COMPRIMENTO_FUSELAGEM-CENTRO_AERODINAMICO)
FORCA_HORIZONTAL = CARGA_EMPENAGEM_HORIZONTAL/2