from Constantes import *

MOMENTO_EMPENAGEM_HORIZONTAL = 0.5*DENSIDADE*VELOCIDADE_DO_AVIAO**2*AREA_ALAR*CORDA_MEDIA*COEFICIENTE_DE_MOMENTO
CARGA_EMPENAGEM_HORIZONTAL = (MOMENTO_EMPENAGEM_HORIZONTAL-FATOR_DE_CARGA*PESO*CENTRO_GRAVIDADE)/(COMPRIMENTO_FUSELAGEM-CENTRO_AERODINAMICO)
FORCA_HORIZONTAL = CARGA_EMPENAGEM_HORIZONTAL/2

z = 0

#Cargas de inercia
FORCA_1 = MASSA_INERCIA_1*ACELERACAO_GRAVITICA*FATOR_DE_CARGA
FORCA_2 = MASSA_INERCIA_2*ACELERACAO_GRAVITICA*FATOR_DE_CARGA
FORCA_3 = MASSA_INERCIA_3*ACELERACAO_GRAVITICA*FATOR_DE_CARGA

def Obter_Forcas(z):
    #Forcas em X
    if 0 <= z <= COMPRIMENTO_FUSELAGEM:
        forcaX = FORCA_HORIZONTAL

    #Forcas em Y
    if 0 <= z < 0.6:
        forcaY = CARGA_EMPENAGEM_HORIZONTAL-FORCA_3-FORCA_2-FORCA_1
    if 0.6 <= z < 2.2:
        forcaY = CARGA_EMPENAGEM_HORIZONTAL-FORCA_3-FORCA_2
    if 2.2 <= z <= COMPRIMENTO_FUSELAGEM:
        forcaY = CARGA_EMPENAGEM_HORIZONTAL-FORCA_3

    #Momentos em X
    if 0 <= z < 0.6:
        momentoX = (CARGA_EMPENAGEM_HORIZONTAL-FORCA_3)*(5.18-2.2)+(CARGA_EMPENAGEM_HORIZONTAL-FORCA_3-FORCA_2)*(2.2-0.6)+(CARGA_EMPENAGEM_HORIZONTAL-FORCA_3-FORCA_2-FORCA_1)*(0.6-z)
    if 0.6 <= z < 2.2:
        momentoX = (CARGA_EMPENAGEM_HORIZONTAL-FORCA_3)*(5.18-2.2)+(CARGA_EMPENAGEM_HORIZONTAL-FORCA_3-FORCA_2)*(2.2-z)
    if 2.2 <= z <= COMPRIMENTO_FUSELAGEM:
        momentoX = (CARGA_EMPENAGEM_HORIZONTAL-FORCA_3)*(5.18-z)

    #Momentos em Y
    if 0 <= z < 0.6:
        momentoY = FORCA_HORIZONTAL

    return forcaX,forcaY,momentoX,momentoY

print(Obter_Forcas(6))